server:
  port: 8080
  servlet:
    context-path: gms

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: ROOT
    driver-class-name: com.mysql.cj.jdbc.Driver
